---
- hosts: service_DB
  gather_facts: no
  tasks:

        - name: Set Up Database
          import_role:
                  name: database

- hosts: service_APP
  gather_facts: no
  tasks:

        - name: Set DB Host
          set_fact:
                  db_host: "{{ hostvars[groups.service_DB.0].private_ip_address }}"

        - name: Set Up Frontend
          import_role:
                  name: application
